### ISSUE TITLE
Question - handling translations

### ISSUE THREAD

**Issue by pa-0** [Aoi-hosizora/PowerPointArrangeAddin#1]
Hi! I'm just wondering if you used a tool to handle all translations? (I noticed that its available in multiple languages)

**Comment by Aoi-hosizora** [comment]
Hi, I'm sorry for replying so late.

As you can see, I built this addin by VSTO, which is provided by .NET. So of course I can use the .NET resource feature for processing multilingual translation. You can read the following source code to know how to handle multilingualism.

If you feel no problem, please close this issue :P

https://github.com/Aoi-hosizora/PowerPointArrangeAddin/blob/500bb64361965521bab466018cea625284d09b54/PowerPointArrangeAddin/PowerPointArrangeAddin.csproj#L242-L254

https://github.com/Aoi-hosizora/PowerPointArrangeAddin/blob/500bb64361965521bab466018cea625284d09b54/PowerPointArrangeAddin/Misc/AddInLanguage.cs#L29-L35

**Comment by pa-0** [comment]
Thanks so much for providing the detail!
